// These modules are code-generated by `smithy-rs`, one in each file. They are model-specific.
pub mod extractors;
pub mod model;
pub mod operation_registry;
pub mod responders;
pub mod service;

// These modules live in a separate `aws-smithy-server` crate in the `smithy-rs` repo, and will
// provide common stuff used by all services i.e. the code here is *not* model-specific.
pub mod router;
pub mod runtime;
