// =============================
// Code-generated by `smithy-rs`
// =============================

use crate::model::*;
use axum::{
    async_trait,
    extract::{FromRequest, RequestParts},
};

#[async_trait]
impl<B> FromRequest<B> for RegisterServiceInput
where
    B: Send,
{
    type Rejection = http::StatusCode;

    async fn from_request(_req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
        todo!()
    }
}

// Same thing for the other operation.

#[async_trait]
impl<B> FromRequest<B> for HealthcheckInput
where
    B: Send,
{
    type Rejection = http::StatusCode;

    async fn from_request(_req: &mut RequestParts<B>) -> Result<Self, Self::Rejection> {
        todo!()
    }
}
