// These modules are code-generated by `smithy-rs`, one in each file. They are model-specific.
pub mod extractors;
pub mod model;
pub mod operation_registry;
pub mod responders;

// These modules live in a separate `aws-smithy-server` crate in the `smithy-rs` repo, and will
// provide common stuff used by all services i.e. the code here is *not* model-specific.
#[macro_use]
pub(crate) mod macros;

pub mod body;
mod clone_box_service;
mod error;
mod handler;
pub mod routing;
pub mod runtime;

pub mod request;
pub mod response;

#[doc(inline)]
pub use self::{error::Error, routing::Router};

/// Alias for a type-erased error type.
pub type BoxError = Box<dyn std::error::Error + Send + Sync>;

#[cfg(test)]
mod test_helpers;
